routes/dashboard.php
<?php

Route::as('home')->get('/', 'HomeController@index');
Route::as('plans')->get('/plans', 'PaymentsController@plans');
Route::as('payments.')->prefix('payments')->group(function() {
	Route::as('pay')->post('pay', 'PaymentsController@pay');
	Route::as('verify')->any('{payment}/verify', 'PaymentsController@verify');
	
	Route::as('verify.result')->any('{status}/verify/{payment}', 'PaymentsController@result');
});

Route::as('account.')->prefix('account')->group(function() {
	Route::as('subscribe')->post('subscribe')->uses('AccountController@subscribe');
	Route::as('subscription.verify')->any('subscription/{payment}/verify')->uses('AccountController@subscriptionVerify');
	Route::as('subscription.result')->get('subscription/{status}/verify/{payment}')->uses('AccountController@subscriptionResult');
});

Route::as('incomes.')->prefix('incomes')->namespace('\Incomes')->group(function() {
	Route::as('banks.report')->get('banks/report')->uses('BanksController@report');
	Route::as('chests.report')->get('chests/report')->uses('ChestsController@report');
	Route::as('checks.report')->get('checks/report')->uses('ChecksController@report');
	
	Route::resource('banks', 'BanksController', ['parameters' => ['bank' => 'turnover']]);
	Route::resource('chests', 'ChestsController', ['parameters' => ['chest' => 'turnover']]);
	Route::as('checks.manage')->get('checks/manage', 'ChecksController@manage');
	Route::as('checks.pass')->get('checks/{turnover}/pass', 'ChecksController@pass');
	Route::as('checks.pass')->put('checks/{turnover}/pass', 'ChecksController@passStore');
	Route::as('checks.spend')->get('checks/{turnover}/spend', 'ChecksController@spend');
	Route::as('checks.spend')->put('checks/{turnover}/spend', 'ChecksController@spendStore');
	Route::resource('checks', 'ChecksController', ['parameters' => ['check' => 'turnover']]);
});
Route::as('outcomes.')->prefix('outcomes')->namespace('\Outcomes')->group(function() {
	Route::resource('banks', 'BanksController', ['parameters' => ['bank' => 'turnover']]);
	Route::resource('chests', 'ChestsController', ['parameters' => ['chest' => 'turnover']]);
	Route::resource('checks', 'ChecksController', ['parameters' => ['checkt' => 'turnover']]);
});

// Route::as('.incomes.bank')->get('incomes/bank/create', 'IncomesController@bankCreate');
// Route::as('.incomes.chest')->get('incomes/chest/create', 'IncomesController@chestCreate');
// Route::as('.incomes.check')->get('incomes/check/create', 'IncomesController@checkCreate');
// Route::as('.outcomes.bank')->get('outcomes/bank/create', 'OutcomesController@bankCreate');
// Route::as('.outcomes.chest')->get('outcomes/chest/create', 'OutcomesController@chestCreate');
// Route::as('.outcomes.check')->get('outcomes/check/create', 'OutcomesController@checkCreate');
// Route::get('outcomes/bank/create', 'OutcomesController@bankCreate');
// Route::get('outcomes/chest/create', 'OutcomesController@chestCreate');
// Route::resource('incomes', 'IncomesController');
// Route::resource('outcomes', 'OutcomesController');

Route::resource('factors/sell', 'SellFactorsController', ['parameters' => ['sell' => 'factor']]);
Route::resource('factors/buy', 'BuyFactorsController', ['parameters' => ['buy' => 'factor']]);
Route::resource('factors', 'FactorsController', ['except' => 'show']);
Route::resource('expenses', 'ExpensesController');

Route::as('spend_items.search')->get('spend_items/search')->uses('SpendItemsController@search');
Route::resource('spend_items', 'SpendItemsController');
Route::resource('chests', 'ChestsController', ['except' => 'show']);
Route::resource('checks', 'ChecksController', ['except' => 'show']);
Route::resource('bank_accounts', 'BankAccountsController', ['except' => 'show']);

Route::as('goods.search')->get('goods/search')->uses('GoodsController@search');
Route::as('goods.childs')->get('goods/{good}/childs')->uses('GoodsController@index');
Route::as('goods.trades')->get('goods/{good}/trades')->uses('GoodsController@trades');
Route::resource('goods', 'GoodsController');

Route::as('warehouses.goods')->get('warehouses/{warehouse}/goods')->uses('WarehousesController@goods');
Route::resource('warehouses', 'WarehousesController', ['except' => 'show']);

Route::as('customers.search')->get('customers/search')->uses('CustomersController@search');
Route::resource('customers', 'CustomersController');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {return view('home'); });
Route::get('about', ['as' => 'about', 'uses' => function () {return view('about'); }]);
Route::get('services', ['as' => 'services', 'uses' => function () {return view('services'); }]);
Route::get('account', ['as' => 'account', 'uses' => function () {return view('faq'); }]);
Route::get('faq', ['as' => 'faq', 'uses' => function () {return view('faq'); }]);
Route::get('contact', ['as' => 'contact', 'uses' => function () {return view('contact'); }]);
Route::get('prices', ['as' => 'prices', 'uses' => function () {return view('prices'); }]);
Route::get('privacy', ['as' => 'privacy', 'uses' => function () {return view('privacy'); }]);
Route::get('complains', ['as' => 'complains', 'uses' => function () {return view('complains'); }]);
// Route::get('account', ['as' => 'account', 'uses' => function () {return view('home'); }]);

// Route::get('/', function () {
// 	dump(Request::route('account'));
//     return view('welcome');
// });

Route::prefix('api/v1')->group(function () {
    Route::get('test', function () {
        dump(Request::route('account'), url()->current(), explode('//', Request::root())[1]);
        dd('system', App\System\Models\User::all());
    });
});

Auth::routes();

Route::get('/home', 'SystemHomeController@index')->name('home');

app/Http/Controllers/Dashboard/AccountController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Carbon\Carbon;

use Zarinpal\Laravel\Facade\Zarinpal;

use App\Tenant\Models\Payment;
use App\Tenant\Models\Subscription;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AccountController extends Controller
{
	public function plans()
	{
		return view('dashboard.payments.prices');
	}

	public function subscribe(Request $request)
	{
		$payment = Payment::create(['amount' => 200000]);		

        $response = Zarinpal::request(
            route('dashboard.account.subscription.verify', $payment->id),
            $payment->amount,
            'پرداخت کیاراد'
        );
        
        if(isset($response['Authority'])) {
            $authority = $response['Authority'];
            return Zarinpal::redirect($authority);
        }

        return 'Error, Status: '.$response['error'];
	}

	public function subscriptionVerify(Request $request, Payment $payment)
	{
        if(is_null($payment->status) || empty($payment->status)){        	
            $response = Zarinpal::verify(
	        	$request->Status,    // $_GET['Status']
	        	$payment->amount,
	        	$request->Authority // $_GET['Authority']
	        );
            if(isset($response) && ($response['Status'] === 'verified_before' || $response['Status'] === 'success')) {
                $payment['transaction_code'] = $response['RefID'];
                $payment['status'] = 100;
                // $payment['message'] = $response['Message'];
                $payment->save();

                if(!$payment->factor_credit) {
                    $last = Subscription::orderByDesc('expired_at')->firstOrNew(['expired_at' => Carbon::now()]);
                    $subscription = $payment->subscription()->create(['expired_at' => $last->expired_at->addYear(1)]);    
                    $credit = $payment->factor_credit()->create(['buy_factor' => 200, 'sell_factor' => 200]);
                }
            }else{
                // Log::alert('Zarinpal Error message: '.($response['status'] ?? print_r($response)).(json_encode($payment)));
                // dump($response);

                $payment['status'] = $response['Status'];
                // $payment['message'] = $response['Message'];
                $payment->save();
            }
        }

        return redirect()->route('dashboard.account.subscription.result', [$payment['status'] === 100 ? 'success' : 'fail', 'payment_id' => $payment->id]); 
	}

	public function subscriptionResult($status, Payment $payment)
	{
		return view('dashboard.account.subscription.payment.result', compact('payment'));
	}	
}

app/Http/Controllers/Dashboard/BankAccountsController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Tenant\Models\BankAccount;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Http\Requests\Dashboard\BankAccountRequest;

class BankAccountsController extends Controller
{
	public function index()
	{
		$bank_accounts = BankAccount::all();

		return view('dashboard.bank_accounts.index', compact('bank_accounts'));
	}

	public function create()
	{
		return view('dashboard.bank_accounts.create');
	}

	public function store(BankAccountRequest $request)
	{
		$data = $request->all();

		$bank_account = BankAccount::create($data);

		if(!$bank_account) {
			return back()->withInput()
				->with(['message' => ['type' => 'error', 'text' => 'مشکلی پیش آمده مجدد تلاش کنید.']]);
		}

		return redirect()->route('dashboard.bank_accounts.edit', $bank_account->id);
	}

	public function edit(BankAccount $bank_account)
	{
		return view('dashboard.bank_accounts.edit', compact('bank_account'));
	}

	public function update(BankAccountRequest $request, BankAccount $bank_account)
	{
		$data = $request->all();

		$update = $bank_account->update($data);

		if(!$update) {
			return back()->withInput()
				->with(['message' => ['type' => 'error', 'text' => 'مشکلی پیش آمده مجدد تلاش کنید.']]);
		}

		return back();	
	}

	public function destroy(BankAccount $bank_account)
	{
		$delete = $bank_account->delete();

		if(!$delete) {
			return back()
				->with(['message' => ['type' => 'error', 'text' => 'مشکلی پیش آمده مجدد تلاش کنید.']]);
		}

		return redirect()->route('dashboard.bank_accounts.index');
	}
}

app/Http/Controllers/Dashboard/BuyFactorsController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Validator;
use Route;

use App\Tenant\Models\BuyFactor as Factor;
use App\Tenant\Models\Customer;
use App\Tenant\Models\AccountData;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Http\Requests\Dashboard\BuyFactorRequest as FactorRequest;

class BuyFactorsController extends Controller
{
	public function index(Request $request)
	{		
		$factors = new Factor;

		$official = $request->get('official', -1);
		if($official != -1) {
			$factors = $factors->where('official', $official);
		}

		$factors = $factors->with('customer')->paginate(20);
		
		return view('dashboard.buy_factors.index', compact('factors'));
	}

	public function create()
	{
	    	return view('dashboard.buy_factors.create');
	}

	public function store(FactorRequest $request)
	{
		$data = $request->except(['official', 'user', 'customer', 'goods']);
		$data['official'] = $request->get('official', false);

		if($data['official']) {
			$data['number'] *= -1;
		}

		$customer = Customer::find($data['customer_id']);

		if($data['official']) {
			$validator = $this->customValidate($request->only(['customer', 'user']), $customer);

			if ($validator->fails()) {
				return back()->withErrors($validator)->withInput();
			}

			$this->updateDealers($request->only(['customer', 'user']), $customer);
		}

		$factor = Factor::create($data);

		$totals = $factor->addGoods($request->goods);
		$update = $factor->update($totals);
		
		return redirect()->route('dashboard.buy.create');
		// return redirect()->route('dashboard.buy.edit', $factor->id);
	}

	public function edit($factor)
	{
		$factor = Factor::with('goods', 'customer', 'customer.data')->find($factor);

		return view('dashboard.buy_factors.edit', compact('factor'));
	}

	public function update(FactorRequest $request, Factor $factor)
	{
		$data = $request->except(['official', 'user', 'customer', 'goods']);
		$data['official'] = $request->get('official', false);

		if($data['official']) {
			$data['number'] *= -1;
		}
		
		$customer = Customer::find($data['customer_id']);

		if($request->get('official', false)) {
			$validator = $this->customValidate($request->only(['customer', 'user']), $customer);

			if ($validator->fails()) {
				return back()->withErrors($validator)->withInput();
			}

			$this->updateDealers($request->only(['customer', 'user']), $customer);
		}

		$update = $factor->update($data);

		$factor->goods()->detach();
		$totals = $factor->addGoods($request->goods);
		$update = $factor->update($totals);
		
		return back();
	}



	public function updateDealers($data, $customer)
	{

		if(isset($data['user'])) {
			foreach($data['user'] as $key => $value){
				AccountData::create(['key' => $key, 'value' => $value]);
			}
		}

		if(isset($data['customer'])) {
			$fields = ['address', 'phone', 'mobile', 'address'];
			$customer->update(array_only($data['customer'], $fields));
			foreach(array_except($data['customer'], $fields) as $key => $value){
				$customer->data()->create(['key' => $key, 'value' => $value]);
			}
		}
	}

	private function customValidate($data, $customer)
	{
		$rules = [];
		
		if(!AccountData::where('key', 'id_number')->exists()) 
			$rules['user.id_number'] = ['required', 'regex:/^\d{10}$/'];
		if(!AccountData::where('key', 'address')->exists())
			$rules['user.address'] = 'required|string';

		if($customer->type->name == 'person') {
			if(!$customer->id_number) $rules['customer.id_number'] = ['required', 'regex:/^\d{10}$/'];
		} else {
			if(!$customer->national_number) $rules['customer.national_number'] =  ['required', 'numeric', 'regex:/^\d{11}$/'];
			if(!$customer->economic_code) $rules['customer.economic_code'] =  ['required', 'numeric', 'regex:/^\d{12}$/'];
		}
		if(!$customer->mobile) $rules['customer.mobile'] = ['required', 'numeric', 'regex:/^09\d{9}$/'];
		if(!$customer->address) $rules['customer.address'] = 'required|string';
		
		$messages = [
			'user.id_number.regex' => 'شماره ملی شما ۱۰ رقم نمیباشد',
			'customer.mobile.regex' => 'شماره موبایل مشتری صحیح نمیباشد',
			'customer.id_number.regex' => 'شماره ملی مشتری ۱۰ رقم نمیباشد',
			'customer.national_number.regex' => 'شناسه ملی مشتری ۱۱ رقم نمیباشد',
			'customer.economic_code.regex' => 'کد اقتصادی مشتری ۱۲ رقم نمیباشد'
		];

		$attributes = [
			'user.id_number' => 'شماره ملی شما',
			'user.address' => 'آدرس شما',
			'customer.mobile' => 'شماره موبایل',
			'customer.address' => 'آدرس مشتری',
			'customer.id_number' => 'شماره ملی مشتری',
			'customer.national_number' => 'شناسه ملی',
			'customer.economic_code' => 'کد اقتصادی'
		];

		$validator = Validator::make($data, $rules, $messages);
		$validator->setAttributeNames($attributes);
		
		return $validator;
	}
}

app/Http/Controllers/Dashboard/ChecksController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Tenant\Models\Check;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ChecksController extends Controller
{
	public function create()
	{
		return view('dashboard.checks.create');
	}
}

app/Http/Controllers/Dashboard/ChestsController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Tenant\Models\Chest;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Http\Requests\Dashboard\ChestRequest;

class ChestsController extends Controller
{
	public function index()
	{
		$chests = Chest::all();

		return view('dashboard.chests.index', compact('chests'));
	}

	public function create()
	{
		return view('dashboard.chests.create');
	}

	public function store(ChestRequest $request)
	{
		$data = $request->all();

		$chest = Chest::create($data);

		if(!$chest) {
			return back()->withInput()
				->with(['message' => ['type' => 'error', 'text' => 'مشکلی پیش آمده مجدد تلاش کنید.']]);
		}

		return redirect()->route('dashboard.chests.edit', $chest->id);
	}

	public function edit(Chest $chest)
	{
		return view('dashboard.chests.edit', compact('chest'));
	}

	public function update(ChestRequest $request, Chest $chest)
	{
		$data = $request->all();

		$update = $chest->update($data);

		if(!$update) {
			return back()->withInput()
				->with(['message' => ['type' => 'error', 'text' => 'مشکلی پیش آمده مجدد تلاش کنید.']]);
		}

		return back();		
	}

	public function destroy(Chest $chest)
	{
		$delete = $chest->delete();

		if(!$delete) {
			return back()
				->with(['message' => ['type' => 'error', 'text' => 'مشکلی پیش آمده مجدد تلاش کنید.']]);
		}

		return redirect()->route('dashboard.chests.index');	
	}
}

app/Http/Controllers/Dashboard/IncomesController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Tenant\Models\Turnover;
use App\Tenant\Models\Chest;
use App\Tenant\Models\BankAccount;
use App\Tenant\Models\Customer;
use App\Tenant\Models\Bank;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class IncomesController extends Controller
{
	public function chestCreate()
	{
		$chests = Chest::all();
		$customers = Customer::all();
		return view('dashboard.incomes.chest.create', compact('chests', 'customers'));
	}

	public function bankCreate()
	{
		$bank_accounts = BankAccount::all();
		$customers = Customer::all();
		return view('dashboard.incomes.bank.create', compact('bank_accounts', 'customers'));
	}

	public function checkCreate()
	{
		$banks = Bank::all();
		$customers = Customer::all();
		return view('dashboard.incomes.check.create', compact('banks', 'customers'));
	}
}

resources/views/dashboard/customers/create.blade.php
@extends('dashboard.layouts.dashboard')

@section('page_title', 'ایجاد مشتری جدید')

@section('page_content')
<div class="row">
	<div class="col-md-8 col-md-push-2">
		@include('dashboard.partials.errors')
		
		<div class="portlet light">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-gift"></i>  ایجاد مشتری جدید
				</div>
			</div>
			<div class="portlet-body form">
				<form action="{{ route('dashboard.customers.store') }}" method="POST" class="form-horizontal">
					{{ csrf_field() }}
					
					@php
						$data = empty(old()) ? new App\Tenant\Models\Customer : old();
						$data['disabled'] = false;
					@endphp
					<div class="form-body">
						@include('dashboard.customers.form', ['data' => $data])
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
@endsection

@section('page_scripts')
<script>
	$(function() {
		$('#person-type-tab a').on('click', function(e) {
			$('input[name=type_id]').val($(this).data('id'));
		});	
	});
</script>
@endsection

resources/views/dashboard/customers/edit.blade.php
@extends('dashboard.layouts.dashboard')

@section('page_title', 'اصلاح اطلاعات مشتری')

@section('page_content')
<div class="row">
	<div class="col-md-8 col-md-push-2">
		@include('dashboard.partials.errors')
		
		<div class="portlet light">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-gift"></i>  اصلاح اطلاعات مشتری
				</div>
				<div class="actions">
					@include('dashboard.partials.buttons.delete', ['route' => 'dashboard.customers.destroy', 'id' => $customer->id])
				</div>
			</div>
			<div class="portlet-body form">
				<form action="{{ route('dashboard.customers.update', $customer->id) }}" method="POST" class="form-horizontal">
					{{ csrf_field() }}
					{{ method_field('PUT') }}

					@php
						if(empty(old())){
							$data = $customer;
							$data['data'] = $customer->data->pluck('value', 'key');
						}else{
							$data = old();
							$data['code'] = $customer->code;
						}
						$data['disabled'] = true;
					@endphp

					<div class="form-body">
						@include('dashboard.customers.form', ['data' => $data])
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
@endsection

@section('page_scripts')
<script>
	$(function() {
		$('#person-type-tab a').on('click', function(e) {
			$('input[name=type_id]').val($(this).data('id'));
		});	
	});
</script>
<script src="{{ asset('metronic/js/helpers.js') }}"></script>
@endsection

resources/views/dashboard/customers/form.blade.php
<ul class="nav nav-tabs nav-justified" id="person-type-tab">
	@foreach($types as $type)
		<li class="{{ ($data['type_id'] ? $data['type_id'] == $type->id : $loop->first) ? 'active' : '' }}">	
			<a href="#tab_{{ $type->id }}" data-toggle="tab" data-id="{{ $type->id }}"> 
				{{ $type->label }} 
			</a>				
		</li>
	@endforeach
</ul>
<input type="hidden" name="type_id" value="{{ $data['type_id'] ?? $types->first()->id }}">
<div class="form-group">
	<label class="control-label col-md-3">کد مشتری:</label>
	<div class="col-md-9">
		@if($data['disabled'])
		<input class="form-control" type="text" value="{{ $data['code'] }}" disabled>
		@else
		<input class="form-control" type="text" name="code" placeholder="کد مشتری" value="{{ $data['code'] }}" required>
		@endif		
	</div>
</div>
<div class="form-group">
	<label class="control-label col-md-3">نام مشتری:</label>
	<div class="col-md-9">
		<input class="form-control" type="text" name="name" placeholder="نام مشتری" value="{{ $data['name'] }}" autocomplete="off" required>		
	</div>
</div>
<div class="form-group">
	<label class="control-label col-md-3">تلفن:</label>
	<div class="col-md-7">
		<input class="form-control" type="text" name="phone"  placeholder="تلفن" value="{{ $data['phone'] }}">		
	</div>
	<div class="col-md-2">
		<input class="form-control" type="text" name="state_code"  placeholder="کد شهر" value="{{ $data['state_code'] }}">		
	</div>
</div>
<div class="form-group">
	<label class="control-label col-md-3">موبایل:</label>
	<div class="col-md-9">
		<input class="form-control" type="text" name="mobile"  placeholder="موبایل" value="{{ $data['mobile'] }}">		
	</div>
</div>
<div class="form-group">
	<label class="control-label col-md-3">آدرس:</label>
	<div class="col-md-9">
		<textarea class="form-control" name="address" rows="2" placeholder="آدرس">{{ $data['address'] }}</textarea>
	</div>
</div>
<hr>
<div class="tab-content">
	<div class="tab-pane {{ ($data['type_id'] ? $data['type_id'] == 1 : true) ? 'active' : '' }}" id="tab_1">
		<div class="form-group">
			<label class="control-label col-md-3">کد ملی:</label>
			<div class="col-md-9">
				<input class="form-control" type="text" name="data[id_number]"  placeholder="کد ملی" value="{{ $data['data']['id_number'] ?? null }}">		
			</div>
		</div>
	</div>
	<div class="tab-pane {{ ($data['type_id'] ? $data['type_id'] == 2 : false) ? 'active' : '' }}" id="tab_2">
		<div class="form-group">
			<label class="control-label col-md-3">کد اقتصادی:</label>
			<div class="col-md-9">
				<input class="form-control" type="text" name="data[economic_code]"  placeholder="کد اقتصادی" value="{{ $data['data']['economic_code'] ?? null }}">		
			</div>
		</div>
		<div class="form-group">
			<label class="control-label col-md-3">شناسه ملی:</label>
			<div class="col-md-9">
				<input class="form-control" type="text" name="data[national_number]"  placeholder="شناسه ملی" value="{{ $data['data']['national_number'] ?? null }}">		
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-9 col-md-push-3">
		<button class="btn btn-success">ذخیره</button>
	</div>
</div>

resources/views/dashboard/customers/index.blade.php
@extends('dashboard.layouts.dashboard')

@section('page_title', ' لیست مشتریان')

@section('page_content')
<div class="row">
	<div class="col-md-8 col-md-push-2">
		<div class="portlet light">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-gift"></i>  لیست مشتریان
				</div>
				<div class="actions">
					<div class="portlet-input input-inline input-small">
						<form action="{{ route('dashboard.customers.index', Request::all()) }}">
							@foreach(Request::except('q') as $key => $value)
								<input type="hidden" name="{{ $key }}" value="{{ $value }}">
							@endforeach
							<div class="input-icon right">
								<i class="icon-magnifier"></i>
								<input type="text" class="form-control input-circle" name="q" placeholder="جستجو..." value="{{ Request::get('q') }}"> 
							</div>
						</form>
					</div>
					<a class="btn green" href="{{ route('dashboard.customers.create') }}">+</a>
				</div>
			</div>
			<div class="portlet-body">
				<ul class="nav nav-tabs nav-justified">
					@php $pageType = Request::get('type', 'all'); @endphp
					<li class="{{ $pageType == 'all' ? 'active' : '' }}">	
						<a href="{{ route('dashboard.customers.index') }}"> 
							همه مشتریان
						</a>				
					</li>
					@foreach($types as $type)
					<li class="{{ $pageType == $type->name ? 'active' : '' }}">	
						<a href="{{ route('dashboard.customers.index', ['type' => $type->name]) }}"> 
							{{ $type->label }} 
						</a>				
					</li>
					@endforeach
				</ul>

				<div class="table-scrollable">	
					<table class="table table-bordered table-hover">
						<thead>
							<tr>
								<th>#</th>
								<th>کد مشتری</th>
								<th>نام مشتری</th>
								<th>شخصیت</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							@foreach($customers as $index => $customer)
								<tr>
									<td> {{ $index + 1 }} </td>
									<td> {{ $customer->code }} </td>
									<td> {{ $customer->name }} </td>
									<td> {{ $customer->type->label }} </td>
									<td>
										<a class="btn btn-outline blue" href="{{ route('dashboard.customers.edit', $customer->id) }}">
											<i class="fa fa-pencil"></i>
										</a>
									</td>
								</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection