routes/dashboard.php
<?php

Route::as('home')->get('/', 'HomeController@index');
Route::as('plans')->get('/plans', 'PaymentsController@plans');
Route::as('payments.')->prefix('payments')->group(function() {
	Route::as('pay')->post('pay', 'PaymentsController@pay');
	Route::as('verify')->any('{payment}/verify', 'PaymentsController@verify');
	
	Route::as('verify.result')->any('{status}/verify/{payment}', 'PaymentsController@result');
});

Route::as('account.')->prefix('account')->group(function() {
	Route::as('subscribe')->post('subscribe')->uses('AccountController@subscribe');
	Route::as('subscription.verify')->any('subscription/{payment}/verify')->uses('AccountController@subscriptionVerify');
	Route::as('subscription.result')->get('subscription/{status}/verify/{payment}')->uses('AccountController@subscriptionResult');
});

Route::as('incomes.')->prefix('incomes')->namespace('\Incomes')->group(function() {
	Route::as('banks.report')->get('banks/report')->uses('BanksController@report');
	Route::as('chests.report')->get('chests/report')->uses('ChestsController@report');
	Route::as('checks.report')->get('checks/report')->uses('ChecksController@report');
	
	Route::resource('banks', 'BanksController', ['parameters' => ['bank' => 'turnover']]);
	Route::resource('chests', 'ChestsController', ['parameters' => ['chest' => 'turnover']]);
	Route::as('checks.manage')->get('checks/manage', 'ChecksController@manage');
	Route::as('checks.pass')->get('checks/{turnover}/pass', 'ChecksController@pass');
	Route::as('checks.pass')->put('checks/{turnover}/pass', 'ChecksController@passStore');
	Route::as('checks.spend')->get('checks/{turnover}/spend', 'ChecksController@spend');
	Route::as('checks.spend')->put('checks/{turnover}/spend', 'ChecksController@spendStore');
	Route::resource('checks', 'ChecksController', ['parameters' => ['check' => 'turnover']]);
});
Route::as('outcomes.')->prefix('outcomes')->namespace('\Outcomes')->group(function() {
	Route::resource('banks', 'BanksController', ['parameters' => ['bank' => 'turnover']]);
	Route::resource('chests', 'ChestsController', ['parameters' => ['chest' => 'turnover']]);
	Route::resource('checks', 'ChecksController', ['parameters' => ['checkt' => 'turnover']]);
});

// Route::as('.incomes.bank')->get('incomes/bank/create', 'IncomesController@bankCreate');
// Route::as('.incomes.chest')->get('incomes/chest/create', 'IncomesController@chestCreate');
// Route::as('.incomes.check')->get('incomes/check/create', 'IncomesController@checkCreate');
// Route::as('.outcomes.bank')->get('outcomes/bank/create', 'OutcomesController@bankCreate');
// Route::as('.outcomes.chest')->get('outcomes/chest/create', 'OutcomesController@chestCreate');
// Route::as('.outcomes.check')->get('outcomes/check/create', 'OutcomesController@checkCreate');
// Route::get('outcomes/bank/create', 'OutcomesController@bankCreate');
// Route::get('outcomes/chest/create', 'OutcomesController@chestCreate');
// Route::resource('incomes', 'IncomesController');
// Route::resource('outcomes', 'OutcomesController');

Route::resource('factors/sell', 'SellFactorsController', ['parameters' => ['sell' => 'factor']]);
Route::resource('factors/buy', 'BuyFactorsController', ['parameters' => ['buy' => 'factor']]);
Route::resource('factors', 'FactorsController', ['except' => 'show']);
Route::resource('expenses', 'ExpensesController');

Route::as('spend_items.search')->get('spend_items/search')->uses('SpendItemsController@search');
Route::resource('spend_items', 'SpendItemsController');
Route::resource('chests', 'ChestsController', ['except' => 'show']);
Route::resource('checks', 'ChecksController', ['except' => 'show']);
Route::resource('bank_accounts', 'BankAccountsController', ['except' => 'show']);

Route::as('goods.search')->get('goods/search')->uses('GoodsController@search');
Route::as('goods.childs')->get('goods/{good}/childs')->uses('GoodsController@index');
Route::as('goods.trades')->get('goods/{good}/trades')->uses('GoodsController@trades');
Route::resource('goods', 'GoodsController');

Route::as('warehouses.goods')->get('warehouses/{warehouse}/goods')->uses('WarehousesController@goods');
Route::resource('warehouses', 'WarehousesController', ['except' => 'show']);

Route::as('customers.search')->get('customers/search')->uses('CustomersController@search');
Route::resource('customers', 'CustomersController');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {return view('home'); });
Route::get('about', ['as' => 'about', 'uses' => function () {return view('about'); }]);
Route::get('services', ['as' => 'services', 'uses' => function () {return view('services'); }]);
Route::get('account', ['as' => 'account', 'uses' => function () {return view('faq'); }]);
Route::get('faq', ['as' => 'faq', 'uses' => function () {return view('faq'); }]);
Route::get('contact', ['as' => 'contact', 'uses' => function () {return view('contact'); }]);
Route::get('prices', ['as' => 'prices', 'uses' => function () {return view('prices'); }]);
Route::get('privacy', ['as' => 'privacy', 'uses' => function () {return view('privacy'); }]);
Route::get('complains', ['as' => 'complains', 'uses' => function () {return view('complains'); }]);
// Route::get('account', ['as' => 'account', 'uses' => function () {return view('home'); }]);

// Route::get('/', function () {
// 	dump(Request::route('account'));
//     return view('welcome');
// });

Route::prefix('api/v1')->group(function () {
    Route::get('test', function () {
        dump(Request::route('account'), url()->current(), explode('//', Request::root())[1]);
        dd('system', App\System\Models\User::all());
    });
});

Auth::routes();

Route::get('/home', 'SystemHomeController@index')->name('home');

app/Http/Controllers/Dashboard/ChecksController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Tenant\Models\Check;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ChecksController extends Controller
{
	public function create()
	{
		return view('dashboard.checks.create');
	}
}

app/Http/Controllers/Dashboard/Incomes/ChecksController.php
<?php

namespace App\Http\Controllers\Dashboard\Incomes;

use App\Tenant\Models\Check;
use App\Tenant\Models\Turnover;
use App\Tenant\Models\Customer;
use App\Tenant\Models\BankAccount;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Dashboard\BankTurnoverRequest;
use App\Http\Requests\Dashboard\CheckTurnoverRequest;

class ChecksController extends Controller
{
	public function index()
	{
		$transactions = Turnover::income()->ofType('check')->paginate(20);

		return view('dashboard.turnovers.index', compact('transactions'));
	}

	public function report(Request $request)
	{
		$transactions = Turnover::income()->ofType('check');

		$transactions = $transactions->filter($request);		
		if($request->has('number') && $request->number) {
			$transactions = $transactions->whereHas('checks', function($query) use ($request) {
				$query->where('number', $request->number);
			});
		}
		if($request->has('begin_due') && !empty($request->begin_due)) {
			$transactions = $transactions->whereHas('checks', function($query) use ($request) {
				$query->where('due_at', '>=', $request->begin_due);
			});
			// dd('here');
		}
		if($request->has('end_due') && !empty($request->end_due)) {
			$transactions = $transactions->whereHas('checks', function($query) use ($request) {
				$query->where('due_at', '<=', $request->end_due);
			});
			// dd('here');
		}

		$transactions = $transactions->paginate(100);

		
		return view('dashboard.turnovers.incomes.check.report', compact('transactions'));
	}

	public function manage(Request $request)
	{
		$transactions = Turnover::with('transaction', 'customer')->income()->ofType('check')
						->join('customers', 'customers.id', '=', 'turnovers.customer_id')
						->join('checks', function ($join) {
							$join->on('checks.id', '=', 'turnovers.transaction_id')
								->where('turnovers.transaction_type', '=', \App\Tenant\Models\Check::class);
						})->select(['turnovers.*', 'customers.name', 'checks.due_at']);

		switch ($request->get('order_by')) {
			case 'due':
				$transactions = $transactions->orderBy('checks.due_at', $request->get('order', 'desc'));
				break;
			case 'customer':
				$transactions = $transactions->orderBy('customers.name', $request->get('order', 'desc'));
				break;
			default:
				$transactions = $transactions->orderBy('turnovers.turnedover_at', $request->get('order', 'desc'));
				break;
		}

		$transactions = $transactions->paginate(20);

		return view('dashboard.turnovers.incomes.check.manage', compact('transactions'));	
	}

	public function spend($turnover)
	{
		$turnover = Turnover::with('transaction')->find($turnover);

		return view('dashboard.turnovers.incomes.check.spend', compact('turnover'));		
	}

	public function spendStore(Request $request, Turnover $turnover)
	{
		$check = $turnover->transaction;

		$data = $request->except('check');		
		$data['transaction_id'] = $turnover->transaction->id;		
		$data['transaction_type'] = Check::class;		
		$data['type'] = 'CHECK';
		$data['income'] = false;

		$turnover = Turnover::create($data);

		if(!$turnover) {
			return back()->withInput()
				->with(['message' => ['type' => 'error', 'text' => 'مشکلی پیش آمده مجدد تلاش کنید.']]);
		}

		$check->transfered_id = $turnover->customer_id;
		$check->transfered_type = Customer::class;
		$check->save();

		return redirect()->route('dashboard.incomes.checks.manage');	
	}

	public function pass($turnover)
	{
		$turnover = Turnover::with('transaction')->find($turnover);

		return view('dashboard.turnovers.incomes.check.pass', compact('turnover'));
	}

	public function passStore(Request $request, Turnover $turnover)
	{
		$check = $turnover->transaction;

		$data = $request->all();				
		$data['transaction_type'] = BankAccount::class;		
		$data['customer_id'] = $turnover->customer_id;
		$data['type'] = 'BANK_ACCOUNT';
		$data['income'] = false;

		$turnover = Turnover::create($data);

		if(!$turnover) {
			return back()->withInput()
				->with(['message' => ['type' => 'error', 'text' => 'مشکلی پیش آمده مجدد تلاش کنید.']]);
		}

		$check->transfered_id = $turnover->transaction_id;
		$check->transfered_type = BankAccount::class;
		$check->save();

		return redirect()->route('dashboard.incomes.checks.manage');
	}

	public function create()
	{
		return view('dashboard.turnovers.incomes.check.create');
	}

	public function store(CheckTurnoverRequest $request)
	{
		$check = Check::create($request->check);
		
		$data = $request->except('check');
		$data['transaction_id'] = $check->id;		
		$data['transaction_type'] = Check::class;		
		$data['type'] = 'CHECK';

		$turnover = Turnover::create($data);

		if(!$turnover) {
			return back()->withInput()
				->with(['message' => ['type' => 'error', 'text' => 'مشکلی پیش آمده مجدد تلاش کنید.']]);
		}

		return redirect()->route('dashboard.incomes.checks.edit', $turnover->id);
	}

	public function edit($turnover)
	{
		$turnover = Turnover::with('transaction')->find($turnover);
		$turnover->check = $turnover->transaction;

		return view('dashboard.turnovers.incomes.check.edit', compact('turnover'));
	}

	public function update(CheckTurnoverRequest $request, $turnover)
	{
		$turnover = Turnover::find($turnover);
		$check = $turnover->checks;

		$check->update($request->check);
		
		$data = $request->except('check');
		$data['transaction_type'] = Check::class;		
		
		$update = $turnover->update($data);

		if(!$update) {
			return back()->withInput()
				->with(['message' => ['type' => 'error', 'text' => 'مشکلی پیش آمده مجدد تلاش کنید.']]);
		}

		return back();
	}

	public function destroy($turnover)
	{
		$turnover = Turnover::find($turnover);

		$delete = $turnover->delete();

		if(!$delete) {
			return back()
				->with(['message' => ['type' => 'error', 'text' => 'مشکلی پیش آمده مجدد تلاش کنید.']]);
		}

		return back();
	}
}

app/Http/Controllers/Dashboard/Outcomes/BanksController.php
<?php

namespace App\Http\Controllers\Dashboard\Outcomes;

use App\Tenant\Models\BankAccount;
use App\Tenant\Models\Turnover;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Dashboard\BankTurnoverRequest;

class BanksController extends Controller
{
	public function index()
	{
		$transactions = Turnover::outcome()->ofType('bank')->paginate(20);

		return view('dashboard.turnovers.index', compact('transactions'));
	}

	public function create()
	{
		return view('dashboard.turnovers.outcomes.bank.create');
	}

	public function store(BankTurnoverRequest $request)
	{
		$data = $request->all();		
		$data['transaction_type'] = BankAccount::class;		
		$data['type'] = 'BANK_ACCOUNT';
		$data['income'] = false;

		$turnover = Turnover::create($data);

		if(!$turnover) {
			return back()->withInput()
				->with(['message' => ['type' => 'error', 'text' => 'مشکلی پیش آمده مجدد تلاش کنید.']]);
		}

		return redirect()->route('dashboard.outcomes.banks.edit', $turnover->id);
	}

	public function edit($turnover)
	{
		$turnover = Turnover::find($turnover);
		
		return view('dashboard.turnovers.outcomes.bank.edit', compact('turnover'));
	}

	public function update(BankTurnoverRequest $request, $turnover)
	{
		$turnover = Turnover::find($turnover);
		
		$data = $request->all();				

		$update = $turnover->update($data);

		if(!$update) {
			return back()->withInput()
				->with(['message' => ['type' => 'error', 'text' => 'مشکلی پیش آمده مجدد تلاش کنید.']]);
		}

		return back();
	}

	public function destroy($turnover)
	{
		$turnover = Turnover::find($turnover);

		$delete = $turnover->delete();

		if(!$delete) {
			return back()
				->with(['message' => ['type' => 'error', 'text' => 'مشکلی پیش آمده مجدد تلاش کنید.']]);
		}

		return back();
	}
}

app/Http/Controllers/Dashboard/Outcomes/ChecksController.php
<?php

namespace App\Http\Controllers\Dashboard\Outcomes;

use App\Tenant\Models\Check;
use App\Tenant\Models\Turnover;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Dashboard\CheckTurnoverRequest;

class ChecksController extends Controller
{
	public function index()
	{
		$transactions = Turnover::outcome()->ofType('check')->paginate(20);

		return view('dashboard.turnovers.index', compact('transactions'));
	}

	public function create()
	{
		return view('dashboard.turnovers.outcomes.check.create');
	}

	public function store(CheckTurnoverRequest $request)
	{
		$check = Check::create($request->check);
		
		$data = $request->except('check');		
		$data['transaction_id'] = $check->id;		
		$data['transaction_type'] = Check::class;		
		$data['type'] = 'CHECK';
		$data['income'] = false;

		$turnover = Turnover::create($data);

		if(!$turnover) {
			return back()->withInput()
				->with(['message' => ['type' => 'error', 'text' => 'مشکلی پیش آمده مجدد تلاش کنید.']]);
		}

		return redirect()->route('dashboard.outcomes.checks.edit', $turnover->id);
	}

	public function edit($turnover)
	{
		$turnover = Turnover::with('transaction')->find($turnover);
		$turnover->check = $turnover->transaction;

		return view('dashboard.turnovers.outcomes.check.edit', compact('turnover'));
	}

	public function update(CheckTurnoverRequest $request, $turnover)
	{
		$turnover = Turnover::with('transaction')->find($turnover);

		$check = $turnover->transaction;
		$update = $check->update($request->check);
		
		$data = $request->except('check');		
		
		$update = $turnover->update($data);

		if(!$update) {
			return back()->withInput()
				->with(['message' => ['type' => 'error', 'text' => 'مشکلی پیش آمده مجدد تلاش کنید.']]);
		}

		return back();
	}

	public function destroy($turnover)
	{
		$turnover = Turnover::find($turnover);

		$delete = $turnover->delete();

		if(!$delete) {
			return back()
				->with(['message' => ['type' => 'error', 'text' => 'مشکلی پیش آمده مجدد تلاش کنید.']]);
		}

		return back();
	}
}

app/Http/Controllers/Dashboard/OutcomesController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Tenant\Models\Turnover;
use App\Tenant\Models\Chest;
use App\Tenant\Models\BankAccount;
use App\Tenant\Models\Customer;
use App\Tenant\Models\Bank;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class OutcomesController extends Controller
{
	public function chestCreate()
	{
		$chests = Chest::all();
		$customers = Customer::all();
		return view('dashboard.outcomes.chest.create', compact('chests', 'customers'));
	}

	public function bankCreate()
	{
		$bank_accounts = BankAccount::all();
		$customers = Customer::all();
		return view('dashboard.outcomes.bank.create', compact('bank_accounts', 'customers'));
	}

	public function checkCreate()
	{
		$banks = Bank::all();
		$customers = Customer::all();
		return view('dashboard.outcomes.check.create', compact('banks', 'customers'));
	}
}

resources/views/dashboard/turnovers/outcomes/check/create.blade.php
@extends('dashboard.layouts.dashboard')

@section('page_title', 'ایجاد پرداختی چک')

@section('page_content')
<div class="row">
	<div class="col-md-8 col-md-push-2">
		@include('dashboard.partials.errors')
		
		<div class="portlet light">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-gift"></i>  ایجاد پرداختی چک
				</div>
			</div>
			<div class="portlet-body form">
				<form action="{{ route('dashboard.outcomes.checks.store') }}" method="POST" class="form-horizontal">
					{{ csrf_field() }}
				
					@php
						$data = empty(old()) ? new App\Tenant\Models\Turnover : old();
					@endphp
					
					<div class="form-body">
						@include('dashboard.turnovers.outcomes.check.form', ['data' => $data])
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/dashboard/turnovers/outcomes/check/edit.blade.php
@extends('dashboard.layouts.dashboard')

@section('page_title', 'اصلاح پرداختی چک')

@section('page_content')
<div class="row">
	<div class="col-md-8 col-md-push-2">
		@include('dashboard.partials.errors')
		
		<div class="portlet light">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-gift"></i>  اصلاح پرداختی چک
				</div>
			</div>
			<div class="portlet-body form">
				<form action="{{ route('dashboard.outcomes.checks.update', $turnover->id) }}" method="POST" class="form-horizontal">
					{{ csrf_field() }}
				
					@php
						$data = empty(old()) ? $turnover : old();
					@endphp
					
					<div class="form-body">
						@include('dashboard.turnovers.outcomes.check.form', ['data' => $data])
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/dashboard/turnovers/outcomes/check/form.blade.php
@section('library_styles')
<link rel="stylesheet" href="{{ asset('assets/global/plugins/typeahead/typeahead.css') }}">
@endsection

<div class="form-group">
	<label class="control-label col-md-3">مشتری:</label>
	<div class="col-md-9">
		<input type="hidden" name="customer_id" value="{{ $data['customer_id'] }}">
		<input type="text" class="form-control" id="customer-typehead">
	</div>
</div>
{{-- <div class="form-group">
	<label class="control-label col-md-3">مشتری:</label>
	<div class="col-md-9">
		<select class="form-control" name="customer_id">
			@foreach($customers as $customer)
				@if($customer->id == $data['customer_id'])
					<option value="{{ $customer->id }}" selected>
				@else
					<option value="{{ $customer->id }}">
				@endif
					{{ $customer->code }} - {{ $customer->name }}
				</option>
			@endforeach
		</select>
	</div>
</div> --}}
<div class="form-group">
	<label class="control-label col-md-3">بانک:</label>
	<div class="col-md-9">
		<select class="form-control" name="check[bank_id]">
			@foreach($banks as $bank)
				@if($bank->id == $data['check']['bank_id'])
					<option value="{{ $bank->id }}" selected>
				@else
					<option value="{{ $bank->id }}">
				@endif
					{{ $bank->name }}
				</option>
			@endforeach
		</select>
	</div>
</div>
<div class="form-group">
	<label class="control-label col-md-3">تاربخ دریافت:</label>
	<div class="col-md-9">
		<input id="date-picker" type="text" class="form-control" value="{{ $data['turnedover_at'] }}" placeholder="تاریخ"/>
		<input type="hidden" name="turnedover_at" id="turnedover-at" value="{{ $data['turnedover_at'] }}">
	</div>
</div>
<div class="form-group">
	<label class="control-label col-md-3">تاربخ چک:</label>
	<div class="col-md-9">
		<input id="check-date-picker" type="text" class="form-control" value="{{ $data['check']['due_at'] }}" placeholder="تاریخ"/>
		<input type="hidden" name="check[due_at]" id="due-at" value="{{ $data['check']['due_at'] }}">
	</div>	
</div>
<div class="form-group">
	<label class="control-label col-md-3">شماره چک:</label>
	<div class="col-md-9">
		<input class="form-control" type="number" name="check[number]" min="0" placeholder="شماره چک" value="{{ $data['check']['number'] }}" required>
	</div>
</div>
<div class="form-group">
	<label class="control-label col-md-3">مبلغ:</label>
	<div class="col-md-9">
		<input class="form-control" type="number" name="amount" min="0" placeholder="مبلغ پرداختی" value="{{ $data['amount'] }}" required>
	</div>
</div>
<div class="form-group">
	<label class="control-label col-md-3">بابت:</label>
	<div class="col-md-9">
		<input class="form-control" type="text" name="description" placeholder="بابت" value="{{ $data['description'] }}">
	</div>
</div>
<div class="row">
	<div class="col-md-9 col-md-push-3">
		<button class="btn btn-success">ثبت</button>
	</div>
</div>

@section('library_scripts')
<script src="{{ asset('js/bloodhound.min.js') }}"></script>
<script src="{{ asset('js/typeahead.bundle.min.js') }}"></script>
@endsection

@section('page_scripts')
<script type="text/javascript">
	var customersSearchUrl = "{{ route('dashboard.customers.search') }}";	
	var customerFetch = "{{ isset($data['customer_id']) && !empty($data['customer_id']) ? 
													route('dashboard.customers.show', $data['customer_id']) : null }}";

  $(document).ready(function() {
    $("#date-picker").pDatepicker({
    	'format': 'dddd DD/MMMM/YYYY',
    	'altField': '#turnedover-at',
    	'altFieldFormatter': function(unix) {
    		var date = new persianDate(unix);
    		var gregorian = date.toCalendar('gregorian');
    		var year = gregorian.year(),
    			month = gregorian.month(),
    			day = gregorian.date();

			return year+'-'+month+'-'+day;
    	}
    });

    $("#check-date-picker").pDatepicker({
    	'format': 'dddd DD/MMMM/YYYY',
    	'altField': '#due-at',
    	'altFieldFormatter': function(unix) {
    		var date = new persianDate(unix);
    		var gregorian = date.toCalendar('gregorian');
    		var year = gregorian.year(),
    			month = gregorian.month(),
    			day = gregorian.date();

			return year+'-'+month+'-'+day;
    	}
    });
  });
</script>
<script src="{{ asset('assets/partials/scripts/customers.js') }}"></script>
@endsection